// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_WPsEp2uYWpREFSE47qiuV4ihuRISXj0',
    appId: '1:352724076123:web:0418a40f618320018e217e',
    messagingSenderId: '352724076123',
    projectId: 'farmconnect-7113c',
    authDomain: 'farmconnect-7113c.firebaseapp.com',
    storageBucket: 'farmconnect-7113c.appspot.com',
    measurementId: 'G-754DEHL0K7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa3QbbK3ylvA1x1hgjGeQzgzHgxzb9oxM',
    appId: '1:352724076123:android:95013027747034ed8e217e',
    messagingSenderId: '352724076123',
    projectId: 'farmconnect-7113c',
    storageBucket: 'farmconnect-7113c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFQyzSbShkAviJaVTmOADQf2GUnuHsJyg',
    appId: '1:352724076123:ios:286cfc548e4152908e217e',
    messagingSenderId: '352724076123',
    projectId: 'farmconnect-7113c',
    storageBucket: 'farmconnect-7113c.appspot.com',
    iosBundleId: 'com.example.farmconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFQyzSbShkAviJaVTmOADQf2GUnuHsJyg',
    appId: '1:352724076123:ios:286cfc548e4152908e217e',
    messagingSenderId: '352724076123',
    projectId: 'farmconnect-7113c',
    storageBucket: 'farmconnect-7113c.appspot.com',
    iosBundleId: 'com.example.farmconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_WPsEp2uYWpREFSE47qiuV4ihuRISXj0',
    appId: '1:352724076123:web:318669f6aac42b748e217e',
    messagingSenderId: '352724076123',
    projectId: 'farmconnect-7113c',
    authDomain: 'farmconnect-7113c.firebaseapp.com',
    storageBucket: 'farmconnect-7113c.appspot.com',
    measurementId: 'G-QRB2PV6F3K',
  );
}
